# Generated by Django 5.2.16 on 2026-07-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitealuno',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Usos Máximos'),
        ),
        migrations.AddField(
            model_name='convitealuno',
            name='use_count',
            field=models.IntegerField(default=0, verbose_name='Usos Atuais'),
        ),
    ]
