# Generated by Django 5.2.16 on 2026-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademiaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=100, verbose_name='Secao')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('idade_min', models.IntegerField(blank=True, null=True, verbose_name='Idade Minima')),
                ('idade_max', models.IntegerField(blank=True, null=True, verbose_name='Idade Maxima')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteudo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parametro da Academia',
                'verbose_name_plural': 'Parametros da Academia',
                'ordering': ['secao', 'ordem', 'titulo'],
            },
        ),
    ]
