# Generated by Django 5.2.16 on 2026-07-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_academiaparametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('permissoes', models.JSONField(blank=True, default=list, verbose_name='Permissões')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Acesso Administrativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
            },
        ),
    ]
