# Generated by Django 5.2.16 on 2026-07-25 01:47

from django.db import migrations


def seed_perfis(apps, schema_editor):
    PerfilAcesso = apps.get_model('parametros', 'PerfilAcesso')
    PerfilAcesso.objects.create(
        nome='ADM - Acesso Total',
        permissoes=[],
        is_admin=True,
    )
    PerfilAcesso.objects.create(
        nome='Professor Padrão',
        permissoes=[
            'ver_alunos', 'criar_alunos', 'editar_alunos',
            'ver_financeiro', 'registrar_pagamento',
            'registrar_graduacao',
            'ver_dashboard',
        ],
        is_admin=False,
    )
    PerfilAcesso.objects.create(
        nome='Professor Financeiro',
        permissoes=[
            'ver_alunos', 'ver_financeiro',
            'registrar_pagamento', 'excluir_pagamento',
            'ver_relatorios',
            'ver_dashboard',
        ],
        is_admin=False,
    )
    PerfilAcesso.objects.create(
        nome='Professor Técnico',
        permissoes=[
            'ver_alunos', 'editar_alunos',
            'registrar_graduacao',
            'ver_dashboard',
        ],
        is_admin=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_perfilacesso'),
    ]

    operations = [
        migrations.RunPython(seed_perfis),
    ]
