# Generated by Django 5.2.16 on 2026-07-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_filial', models.BooleanField(default=True, verbose_name='É Filial?')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('rua', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=255, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['nome'],
            },
        ),
    ]
