# Generated by Django 5.2.16 on 2026-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo')),
                ('arquivo', models.ImageField(blank=True, upload_to='midias/', verbose_name='Arquivo')),
                ('url_youtube', models.URLField(blank=True, verbose_name='URL do YouTube')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mídia de Treino',
                'verbose_name_plural': 'Mídias de Treino',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
