# Generated by Django 5.2.16 on 2026-07-25 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_perfilacesso'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='perfil_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.perfilacesso', verbose_name='Perfil de Acesso'),
        ),
    ]
