# Generated by Django 5.2.16 on 2026-07-24 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('faixa', models.CharField(max_length=50, verbose_name='Faixa')),
                ('grau', models.IntegerField(default=0, verbose_name='Grau')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pausado', 'Pausado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GraduacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_anterior', models.CharField(max_length=50, verbose_name='Faixa Anterior')),
                ('grau_anterior', models.IntegerField(verbose_name='Grau Anterior')),
                ('faixa_nova', models.CharField(max_length=50, verbose_name='Faixa Nova')),
                ('grau_novo', models.IntegerField(verbose_name='Grau Novo')),
                ('graduado_em', models.DateField(verbose_name='Graduado Em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes', to='alunos.aluno')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'ordering': ['-graduado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensalidadePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_mes', models.DateField(verbose_name='Mês de Referência')),
                ('vencimento_em', models.DateField(verbose_name='Vencimento')),
                ('pago_em', models.DateField(blank=True, null=True, verbose_name='Pago Em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-referencia_mes'],
            },
        ),
    ]
