# Generated by Django 5.2.16 on 2026-07-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_dia_vencimento_aluno_valor_mensalidade'),
        ('parametros', '0002_academiaparametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_ultima_graduacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Graduação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.horariotreino', verbose_name='Horário de Treino'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='modalidades',
            field=models.JSONField(blank=True, null=True, verbose_name='Modalidades'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_telefone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone 2 do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tem_responsavel',
            field=models.BooleanField(default=False, verbose_name='Tem Responsável'),
        ),
    ]
