# Generated by Django 5.2.16 on 2026-07-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_data_ultima_graduacao_aluno_horario_treino_and_more'),
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial', verbose_name='Filial'),
        ),
    ]
